version: '2'
services:
  atul-postgres-db:
    image: postgres
    container_name: atul-postgres-db
    environment:
      - POSTGRES_PASSWORD=9812376024
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
    ports:
      - '5432:5432'
    networks:
      host:
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  host:
  
