tables = [
    "arc_reactor_assemblies",
    "aux_batteries",
    "batteries",
    "battery_assemblies",
    "battery_boxes",
    "biws",
    "bmses",
    "bottom_links",
    "brake_pedal_assemblies",
    "brake_plates",
    "brake_switches",
    "calipers",
    "cells",
    "cocktail_box_assemblies",
    "cocktail_boxes",
    "crown_nuts",
    "dc_dcs",
    "disc_brake_assemblies",
    "driveshaft_assemblies",
    "drums",
    "fork_2_bearings",
    "fork_and_suspension_assemblies",
    "front_wheel_assemblies",
    "gearboxes",
    "hub_assemblies",
    "load_bodies",
    "marks",
    "motor_controllers",
    "motors",
    "mounting_rubbers",
    "muff_cups",
    "on_board_chargers",
    "powertrains",
    "rear_axles",
    "rear_suspension_assemblies",
    "rear_wheel_assemblies",
    "reservoirs",
    "rims",
    "rotors",
    "semi_sprung_assemblies",
    "signal_connectors",
    "springs",
    "starks",
    "struts",
    "telematics",
    "tmcs",
    "trailing_arms",
    "tyres",
    "upper_and_lower_cones",
    "vehicle_harnesses",
    "vehicles",
]
sub_assembly_tables = ['biws', 'powertrains', 'semi_sprung_assemblies', 'rear_suspension_assemblies', 'driveshaft_assemblies', 'fork_and_suspension_assemblies', 'disc_brake_assemblies', 'rear_wheel_assemblies', 'front_wheel_assemblies', 'brake_pedal_assemblies', 'vehicle_harnesses', 'marks', 'battery_assemblies', 'cocktail_box_assemblies', 'telematics', 'load_bodies']

component_tables = ['cocktail_boxes', 'aux_batteries', 'motor_controllers', 'on_board_chargers', 'dc_dcs', 'starks', 'arc_reactor_assemblies', 'cells', 'bmses', 'batteries', 'battery_boxes', 'signal_connectors', 'tmcs', 'reservoirs', 'brake_switches', 'tyres', 'rims', 'tyres', 'rims', 'rotors', 'calipers', 'upper_and_lower_cones', 'fork_2_bearings', 'bottom_links', 'springs', 'struts', 'rear_axles', 'crown_nuts', 'springs', 'struts', 'mounting_rubbers', 'trailing_arms', 'drums', 'brake_plates', 'hub_assemblies', 'gearboxes', 'motors', 'muff_cups']

